import { AppSidebar } from "@/components/app-sidebar";
import { SiteHeader } from "@/components/site-header";
import { SidebarInset, SidebarProvider } from "@/components/ui/sidebar";

export default function PrivacyPolicyPage() {
  return (
    <SidebarProvider
      style={
  // @ts-expect-error
        { "--sidebar-width": "calc(var(--spacing) * 72)", "--header-height": "calc(var(--spacing) * 12)" }
      }
    >
      <AppSidebar variant="inset" />
      <SidebarInset>
        <SiteHeader />
        <div className="p-6">
          <h1 className="text-2xl font-bold mb-4">Privacy Policy</h1>

          <h2 className="text-lg font-semibold mt-4">Data Controller</h2>
          <p className="mt-2">Dr. Toste Tanhua<br />
          GEOMAR Helmholtz Centre for Ocean Research Kiel<br />
          Wischhofstr. 1-3<br />
          24148 Kiel, Germany<br />
          E‑mail: info@soop-platform.earth</p>

          <h2 className="text-lg font-semibold mt-4">Editorial team</h2>
          <p className="mt-2">Myriam Dutzi<br />
          Innovation Management & Communication<br />
          GEOMAR Helmholtz Centre for Ocean Research Kiel<br />
          Wischhofstr. 1-3<br />
          24148 Kiel, Germany<br />
          E‑mail: info@soop-platform.earth</p>

          <h2 className="text-lg font-semibold mt-4">General information</h2>
          <p className="mt-2">Protecting your personal data is important to us. In this privacy policy we inform you about the type, scope and purpose of processing personal data on this website.</p>

          <h2 className="text-lg font-semibold mt-4">Collection and storage of personal data</h2>
          <p className="mt-2">When visiting the website, information (so-called server log files) is automatically collected that your browser transmits. This includes, among others, browser type, operating system used, referrer URL, hostname of the accessing computer and the time of the server request. These data are used exclusively to ensure the operation of the site and to analyze system operation.</p>

          <h2 className="text-lg font-semibold mt-4">Use of Google Analytics</h2>
          <p className="mt-2">This website uses Google Analytics (GA4) from Google LLC to analyze website usage. Google Analytics uses cookies which enable an analysis of your use of the website. The information generated by the cookie about your use of this website is generally transmitted to and stored on a Google server in the USA.</p>
          <p className="mt-2">We have integrated Google Analytics in a way that no personal data are transmitted to Google (IP anonymization is enabled). Google Analytics is only used if you consent via the cookie banner. You can prevent the storage of cookies entirely via the settings of your browser or refuse acceptance of cookies. In this case the functionality of this website may be limited.</p>

          <h2 className="text-lg font-semibold mt-4">Cookies</h2>
          <p className="mt-2">We use cookies to improve the usability of the website. Cookies are small text files stored on your device. You can prevent the storage of cookies by changing the settings of your browser.</p>

          <h2 className="text-lg font-semibold mt-4">Legal basis</h2>
          <p className="mt-2">The processing of personal data is carried out in accordance with the General Data Protection Regulation (GDPR). To the extent we obtain consents, the legal basis is Art. 6 para. 1 lit. a GDPR. To the extent processing is necessary for the performance of a contract or pre-contractual measures, the legal basis is Art. 6 para. 1 lit. b GDPR.</p>

          <h2 className="text-lg font-semibold mt-4">Disclosure of data</h2>
          <p className="mt-2">Your data will only be disclosed to third parties if this is necessary to provide the website (e.g. hosting provider) or if you have previously given your consent. Otherwise, no transfer will be made without your consent.</p>

          <h2 className="text-lg font-semibold mt-4">Liability note</h2>
          <p className="mt-2">Despite careful content control, we assume no liability for the content of external links. The operators of the linked pages are solely responsible for their content.</p>

          <h2 className="text-lg font-semibold mt-4">Storage period</h2>
          <p className="mt-2">Personal data will be stored only as long as necessary for the respective purposes or as required by statutory retention periods.</p>

          <h2 className="text-lg font-semibold mt-4">Your rights</h2>
          <p className="mt-2">You have the right to obtain information about the personal data stored about you and, if applicable, the right to request correction, restriction or deletion of this data. Under certain circumstances you may object to the processing of your data or request restriction of processing.</p>

          <h2 className="text-lg font-semibold mt-4">Contact</h2>
          <p className="mt-2">If you have any questions about data protection, you can contact the email address given above.</p>

          <h2 className="text-lg font-semibold mt-4">Changes to this privacy policy</h2>
          <p className="mt-2">We reserve the right to adapt this privacy policy if necessary. The current version can always be found on this page.</p>
        </div>
      </SidebarInset>
    </SidebarProvider>
  );
}
